# Generated by Django 4.1.5 on 2023-01-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('Service Request', 'Service Request'), ('Incident', 'Incident')], default='Service Request', max_length=30),
        ),
    ]
