# Generated by Django 4.1.5 on 2023-01-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketApp', '0002_ticket_ticket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='app_name',
            field=models.CharField(choices=[('Aplication 1', 'App1'), ('Aplication 2', 'App2'), ('Aplication 3', 'App3'), ('Aplication 4', 'App4')], default='Aplication 1', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('In Review', 'In Review'), ('Done', 'Done')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('Service Request', 'Service Request'), ('Incident', 'Incident')], max_length=30),
        ),
    ]
